<a href="https://colab.research.google.com/github/choi-yh/Pyhon_ML_Guide/blob/master/09_00_%EC%B6%94%EC%B2%9C_%EC%8B%9C%EC%8A%A4%ED%85%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01. 추천 시스템의 개요와 배경

### 추천 시스템의 개요

### 온라인 스토어의 필수 요소, 추천 시스템

* 추천 시스템을 통해 소비자가 제품 선택을 손쉽게 할 수 있도록 한다.
* 추천 시스템 구성 예시
    * 사용자가 어떤 상품을 구매했는가?
    * 사용자가 어떤 상품을 둘러보고, 장바구니에 추가했는가?
    * 사용자의 평점은?
    

### 추천 시스템의 유형


* **콘텐츠 기반 필터링(Content based filtering)**
* **협업 필터링(Collaborative Filtering)**
    * 최근접 이웃(Nearest Neighbor) 협업 필터링
    * 잠재 요인(Latent Factor) 협업 필터링


* 추천 시스템 초기에는 콘텐츠 기반 필터링 / 최근접 이웃 협업 필터링 사용
* "넷플릭스 추천 시스템 경연대회"에서 **행렬 분해(Matrix Factorization) 기법을 이용한 잠재 요인 협업 필터링 방식**이 우승 -> 대부분의 온라인 스토어에서 해당 기법을 활용한 시스템 적용 중

## 02. 콘텐츠 기반 필터링 추천 시스템 (Content based filtering)

* **사용자가 특정 아이템 사용을 매우 선호하는 경우, 해당 아이템과 비슷한 콘텐츠를 가진 아이템을 추천하는 방식**  
ex) 특정 영화에 높은 평점을 줬을 경우, 해당 장르, 감독, 배우, 키워드 등이 비슷한 영화를 추천

## 03. 최근접 이웃 협업 필터링

* **협업 필터링(Collaborative Filtering)**:   
 **사용자 행동 양식(User Behavior)**(사용자가 아이템에 매긴 평점, 상품 구매 이력 등)을 기반으로 추천을 수행하는 방식

* 주요 목표: 사용자-아이템 평점 매트릭스와 같은 축적된 사용자 행동 데이터를 기반으로 사용자가 아직 평가하지 않은 아이템을 예측 평가(Predicted Rating)하는 것

* 협업 필터링(Collaborative Filtering) 방식은 **최근접 이웃 방식**과 **잠재 요인 방식**으로 나뉜다. 두 방식 모두 사용자-아이템 평점 행렬 데이터에만 의지해 추천을 수행

* **사용자-아이템 평점 행렬**
    * 행(Row): 개별 사용자
    * 열(Column): 개별 아이템
    * 값(Value): 평점
    * 많은 아이템을 열로 가지는 다차원 행렬이며, 사용자가 평점을 내는 경우가 많지 않기 때문에 **희소 행렬(Sparse Matrix)** 특성을 가지고 있다.

---

* 최근접 이웃 협업 필터링은 메모리(Memory) 협업 필터링이라고도 하며 다음과 같이 나눌 수 있다.
    * **사용자 기반(User-User) 협업 필터링**  
        * 당신과 비슷한 고객들이 다음 상품도 구매 (Customers like you also bought these items.)
        * 특정 사용자와 유사한 다른 사용자를 TOP-N으로 선정해 이 TOP-N 사용자가 좋아하는 아이템을 추천하는 방식
        * 특정 사용자와 타 사용자 간의 유사도(Similarity)를 측정한 뒤 가장 유사도가 높은 TOP-N 사용자를 추출해 그들이 선호하는 아이템을 추천

    * **아이템 기반(Item-Item) 협업 필터링**
        * 이 상품을 선택한 다른 고객들은 다음 상품도 구매 (Customers who bought this item also bought these items.)
        * (아이템이 가지는 속성과는 상관없이) 사용자들이 그 아이템을 좋아하는지/싫어하는지의 평가 척도가 유사한 아이템을 추천하는 기준이 되는 알고리즘
        * 사용자 기반 최근접 이웃 데이터 세트와 행과 열이 서로 반대 (행이 개별 아이템, 열이 개별 사용자)

    * 일반적으로 사용자 기반 협업 필터링보다 **아이템 기반 협업 필터링**이 정확도가 더 높다.  
     비슷한 영화를 좋아한다고 해서 취향이 비슷한 것은 아니고 유명한 영화의 경우 대부분의 사람이 관람을 하기 때문이다. 또한, 사용자들이 평점을 매기지 않은 아이템이 많아 다른 사람들과의 유사도를 비교하기 어렵다.


* **다차원 희소 행렬**이라는 특징이 있기 때문에 텍스트 분석에서 사용하는 **코사인 유사도**를 통해 추천 시스템의 유사도를 측정한다.

---

* **코사인 유사도**(Cosine Similarity)
    * 벡터와 벡터 간의 유사도를 비교할 때, 벡터의 크기보다는 **벡터의 상호 방향성**이 얼마나 유사한지에 기반 (두 벡터 사이의 사잇각을 구해서 얼마나 유사한지 수치로 적용)

$$similarity = cos \theta = \frac{A \cdot B}{\lVert A \rVert \lVert B \rVert} = \frac{\sum_{i=1}^n A_i B_i} {\sqrt{\sum_{i=1}^n A_i^2 } \sqrt{\sum_{i=1}^n  B_i^2}}$$

In [1]:
# 레코드 레벨 형태(row-level 형태)의 데이터는 사용자-아이템 평점 행렬로 바꿔줘야함
# row: 사용자 / column: 아이템

import pandas as pd

data = pd.DataFrame({"User ID": ['User 1', 'User 1', 'User 2', 'User 2', 'User 3'],
                     "Item ID": ['Item 1', 'Item 3', 'Item 1', 'Item 2', 'Item 4'],
                     "Rating": [3, 3, 4, 1, 5]})
display(data)

print('')
print('=' * 50)
print('')

data = pd.pivot_table(data=data, values='Rating', index='User ID', columns='Item ID')
display(data)

User ID Item ID  Rating
0  User 1  Item 1       3
1  User 1  Item 3       3
2  User 2  Item 1       4
3  User 2  Item 2       1
4  User 3  Item 4       5

Item ID  Item 1  Item 2  Item 3  Item 4
User ID                                
User 1      3.0     NaN     3.0     NaN
User 2      4.0     1.0     NaN     NaN
User 3      NaN     NaN     NaN     5.0

In [2]:
# 사용자 기반 최근접 협업 필터링 방식에서 사용하는 데이터 형태
data = pd.DataFrame({"User": ['A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C'],
                     "Movie": ['다크나이트', '인터스텔라', '엣지오브투모로우', '다크나이트', '인터스텔라', '엣지오브투모로우', '프로메테우스', '스타워즈', '다크나이트', '인터스텔라', '엣지오브투모로우', '프로메테우스', '스타워즈'],
                     "Value": [5, 4, 4, 5, 3, 4, 5, 3, 4, 3, 3, 2, 5]})

user_based_data = pd.pivot_table(data=data, values='Value', index='User', columns='Movie')
user_based_data

Movie  다크나이트  스타워즈  엣지오브투모로우  인터스텔라  프로메테우스
User                                       
A        5.0   NaN       4.0    4.0     NaN
B        5.0   3.0       4.0    3.0     5.0
C        4.0   5.0       3.0    3.0     2.0

사용자 기반 최근접 협업 필터링을 사용할 때, A가 관람한 ['다크나이트', '엣지오브투모로우', '인터스텔라'] 평점이 C보다는 B와 유사하므로 B의 평점이 더 높은 프로메테우스를 A에게 추천한다.

In [3]:
# 아이템 기반 최근접 협업 필터링 방식에서 사용하는 데이터 형태
data = pd.DataFrame({"User": ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C', 'D', 'E', 'E', 'E'],
                     "Movie": ['다크나이트', '프로메테우스', '스타워즈', '다크나이트', '프로메테우스', '스타워즈', '다크나이트', '프로메테우스', '스타워즈', '다크나이트', '다크나이트', '프로메테우스', '스타워즈'],
                     "Value": [5, 5, 4, 4, 4, 3, 5, 4, 3, 5, 5, 5, 4]})

item_based_data = pd.pivot_table(data=data, values='Value', index='Movie', columns='User')
item_based_data

User      A    B    C    D    E
Movie                          
다크나이트   5.0  4.0  5.0  5.0  5.0
스타워즈    4.0  3.0  3.0  NaN  4.0
프로메테우스  5.0  4.0  4.0  NaN  5.0

모두에게 평점이 있는 다크나이트를 확인했을 때, 스타워즈보다는 프로메테우스가 평점 분포가 더 비슷하다. => D에게 프로메테우스를 추천

In [4]:
# 코사인 유사도 계산
import numpy as np

def cos_similarity(v1, v2):
    dot_product = np.dot(v1, v2)
    l2_norm = np.sqrt(sum(np.square(v1))) * np.sqrt(sum(np.square(v2)))
    similarity = dot_product / l2_norm

    return similarity

darkknight = np.array([5, 4, 5, 5])
starwarz = np.array([4, 3, 3, 4])
prometheus = np.array([5, 4, 4, 5])

print(f'darkknight with starwarz: {cos_similarity(darkknight, starwarz):.4f}')
print(f'darkknight with prometheus: {cos_similarity(darkknight, prometheus):.4f}')

darkknight with starwarz: 0.9933
darkknight with prometheus: 0.9956


## 04. 잠재 요인 협업 필터링

### 잠재 요인 협업 필터링의 이해

* 잠재 요인 협업 필터링: 사용자-아이템 평점 매트릭스 속에 숨어 있는 잠재 요인을 추출해 추천 예측을 할 수 있게 하는 기법

* **사용자-아이템 평점 매트릭스**와 같은 *다차원 희소 행렬* 을 SVD와 같은 차원 축소 기법을 이용해 행렬을 분해  
 -> *저차원 밀집 행렬* 인 **사용자-잠재 요인 행렬**과 **아이템-잠재 요인 행렬**의 전치 행렬(잠재 요인-아이템 행렬)  
 -> 두 행렬의 내적을 통해 새로운 사용자-아이템 평점 행렬 데이터를 만들어 평점이 없는 아이템에 대한 예측 평점을 생성한다.

* **잠재 요인**에 대해서 명확히 정의는 어렵다. (ex) 영화 평점에 대한 사용자-아이템 평점 매트릭스 분해시 잠재 요인은 **사용자의 해당 장르에 대한 선호도**와 **아이템(영화)의 장르 속성**이 될 수 있다.

* 잠재 요인 협업 필터링은 숨겨져 있는 *잠재 요인* 을 기반으로 분해된 매트릭스를 이용해 사용자가 아직 평가하지 않은 아이템에 대한 예측 평가를 수행하는 것

* **행렬 분해(Matrix Factorization)**: 다차원의 매트릭스를 저차원의 매트릭스로 분해하는 기법

In [43]:
# 행렬 분해를 통한 잠재 요인 협업 필터링

# 사용자-아이템 평점 행렬(R)
r = pd.DataFrame(data=np.array([[4, np.nan, np.nan, 2, np.nan],
                                [np.nan, 5, np.nan, 3, np.nan],
                                [np.nan, np.nan, 3, 4, 4],
                                [5, 2, 1, 2, np.nan]]),
                 columns=['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5'],
                 index=['User 1', 'User 2', 'User 3', 'User 4'])

print(' 사용자-아이템 평점 행렬(R)')
display(r)

# 사용자-잠재 요인 행렬(P)
p = pd.DataFrame(data=np.array([
                                [0.94, 0.96],
                                [2.14, 0.08],
                                [1.93, 1.79],
                                [0.58, 1.59]
                                ]),
                 columns=['factor 1', 'factor 2'],
                 index=['User 1', 'User 2', 'User 3', 'User 4'])

print('=' * 60)
print(' <매트릭스 분해>')
print(' 사용자-잠재 요인 행렬(P)')
display(p)

# 잠재 요인-아이템 행렬(Q)
q_t = pd.DataFrame(data=np.array([[1.7, 2.3, 1.41, 1.36, 0.41],
                                [2.49, 0.41, 0.14, 0.75, 1.77]]),
                 columns=['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5'],
                 index=['factor 1', 'factor 2'])

print(' 잠재 요인-아이템 행렬(Q.T)')
display(q_t)

predict_matrix = pd.DataFrame(data=np.matmul(p.to_numpy(), q_t.to_numpy()),
                              columns=q_t.columns,
                              index=p.index)
print('')
print('=' * 60)
print(' 사용자-잠재 요인 행렬(Q)과 잠재 요인-아이템 행렬(Q.T) 내적 곱을 통한 결과 예측')
display(predict_matrix)

 사용자-아이템 평점 행렬(R)


Item 1  Item 2  Item 3  Item 4  Item 5
User 1     4.0     NaN     NaN     2.0     NaN
User 2     NaN     5.0     NaN     3.0     NaN
User 3     NaN     NaN     3.0     4.0     4.0
User 4     5.0     2.0     1.0     2.0     NaN

 <매트릭스 분해>
 사용자-잠재 요인 행렬(P)


factor 1  factor 2
User 1      0.94      0.96
User 2      2.14      0.08
User 3      1.93      1.79
User 4      0.58      1.59

 잠재 요인-아이템 행렬(Q.T)


Item 1  Item 2  Item 3  Item 4  Item 5
factor 1    1.70    2.30    1.41    1.36    0.41
factor 2    2.49    0.41    0.14    0.75    1.77


 사용자-잠재 요인 행렬(Q)과 잠재 요인-아이템 행렬(Q.T) 내적 곱을 통한 결과 예측


Item 1  Item 2  Item 3  Item 4  Item 5
User 1  3.9884  2.5556  1.4598  1.9984  2.0846
User 2  3.8372  4.9548  3.0286  2.9704  1.0190
User 3  7.7381  5.1729  2.9719  3.9673  3.9596
User 4  4.9451  1.9859  1.0404  1.9813  3.0521

R(u, i)  
P(u, k)  
Q(i, k)



### 행렬 분해의 이해

### 확률적 경사 하강법(SGD, Stochastic Gradient Descent)을 이용한 행렬 분해

In [61]:
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정.
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN],
              [np.NaN, 5, np.NaN, 3, 1],
              [np.NaN, np.NaN, 3, 4, 4],
              [5, 2, 1, 2, np.NaN]])

num_users, num_items = R.shape
K = 3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

In [49]:
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
    error = 0
    # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
    full_pred_matrix = np.dot(P, Q.T)

    # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스를 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)

    return rmse

In [62]:
# R > 0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장
non_zeros = [ (i, j, R[i, j]) for i in range(num_users) for j in range(num_items) if R[i, j] > 0 ]

steps = 1000 # SGD를 반복해서 업데이트할 횟수
learning_rate = 0.01 # SGD 학습률
r_lambda = 0.01 # L2 Regularization 계수

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트
for step in range(steps):
    for i, j, r in non_zeros:
        # 실제 값과 예측 값의 차이인 오류 값 구함
        eij = r - np.dot(P[i, :], Q[j, :].T)
        # Regularization을 반영한 SGD 업데이트 공식 적용
        P[i, :] = P[i, :] + learning_rate * (eij * Q[j, :] - r_lambda * P[i, :])
        Q[j, :] = Q[j, :] + learning_rate * (eij * P[i, :] - r_lambda * Q[j, :])

    rmse = get_rmse(R, P, Q, non_zeros)
    if (step % 100) == 0: # 100회 반복시마다 출력
        print(f'### iteration step: {step}, rmse: {rmse:.4f}')

### iteration step: 0, rmse: 3.2388
### iteration step: 100, rmse: 0.1564
### iteration step: 200, rmse: 0.0433
### iteration step: 300, rmse: 0.0226
### iteration step: 400, rmse: 0.0180
### iteration step: 500, rmse: 0.0170
### iteration step: 600, rmse: 0.0167
### iteration step: 700, rmse: 0.0166
### iteration step: 800, rmse: 0.0165
### iteration step: 900, rmse: 0.0165


In [63]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]
